import albo from "../assets/sellers/1.webp";
import ecom from "../assets/sellers/3.webp";
import delight from "../assets/sellers/4.webp";
import whale from "../assets/sellers/7.webp";
import academy from "../assets/sellers/9.webp";
import oakley from "../assets/sellers/11.webp";

const transactions = [
  {
    sku: "283728371",
    timestamp: new Date().toString(),
    method: "Visa",
    type: "bussiness",
    status: "waiting",
    country: "USA",
    currency: "usd",
    fee: 400,
    tax: Math.random(0, 10),
    seller: {
      name: "Albo E-Store",
      logo: albo,
    },
  },
  {
    sku: "283728372",
    timestamp: new Date().toString(),
    method: "Visa",
    type: "bussiness",
    status: "approved",
    country: "USA",
    currency: "usd",
    fee: 400,
    tax: Math.random(0, 10),
    seller: {
      name: "Ecom",
      logo: ecom,
    },
  },
  {
    sku: "283728373",
    timestamp: new Date().toString(),
    method: "Maestro",
    type: "bussiness",
    status: "approved",
    country: "Australia",
    currency: "usd",
    fee: 400,
    tax: Math.random(0, 10),
    seller: {
      name: "Albo E-Store",
      logo: albo,
    },
  },
  {
    sku: "283728374",
    timestamp: new Date().toString(),
    method: "PayPal",
    type: "bussiness",
    status: "approved",
    country: "Israel",
    currency: "usd",
    fee: 400,
    tax: Math.random(0, 10),
    seller: {
      name: "Ecom",
      logo: ecom,
    },
  },
  {
    sku: "283728375",
    timestamp: new Date().toString(),
    method: "Switch",
    type: "bussiness",
    status: "cancelled",
    country: "Italy",
    currency: "usd",
    fee: 400,
    tax: Math.random(0, 10),
    seller: {
      name: "Delight",
      logo: delight,
    },
  },
  {
    sku: "283728376",
    timestamp: new Date().toString(),
    method: "Visa",
    type: "bussiness",
    status: "rejected",
    country: "USA",
    currency: "usd",
    fee: 400,
    tax: Math.random(0, 10),
    seller: {
      name: "Delight",
      logo: delight,
    },
  },
  {
    sku: "283728377",
    timestamp: new Date().toString(),
    method: "Mastercard",
    type: "bussiness",
    status: "approved",
    country: "France",
    currency: "usd",
    fee: 400,
    tax: Math.random(0, 10),
    seller: {
      name: "Whale",
      logo: whale,
    },
  },
  {
    sku: "283728378",
    timestamp: new Date().toString(),
    method: "PayPal",
    type: "bussiness",
    status: "approved",
    country: "France",
    currency: "usd",
    fee: 400,
    tax: Math.random(0, 10),
    seller: {
      name: "Academy",
      logo: academy,
    },
  },
  {
    sku: "283728379",
    timestamp: new Date().toString(),
    method: "Visa",
    type: "bussiness",
    status: "approved",
    country: "Latvia",
    currency: "usd",
    fee: 400,
    tax: Math.random(0, 10),
    seller: {
      name: "Academy",
      logo: academy,
    },
  },
  {
    sku: "2837283710",
    timestamp: new Date().toString(),
    method: "PayPal",
    type: "bussiness",
    status: "cancelled",
    country: "Poland",
    currency: "usd",
    fee: 400,
    tax: Math.random(0, 10),
    seller: {
      name: "Oakley Store",
      logo: oakley,
    },
  },
  {
    sku: "2837283711",
    timestamp: new Date().toString(),
    method: "Maestro",
    type: "bussiness",
    status: "approved",
    country: "Canada",
    currency: "usd",
    fee: 400,
    tax: Math.random(0, 10),
    seller: {
      name: "Oakley Store",
      logo: oakley,
    },
  },
  {
    sku: "2837283712",
    timestamp: new Date().toString(),
    method: "Mastercard",
    type: "bussiness",
    status: "approved",
    country: "Sweden",
    currency: "usd",
    fee: 400,
    tax: Math.random(0, 10),
    seller: {
      name: "Albo E-Store",
      logo: albo,
    },
  },
];

export default transactions;
